version: '3'

services:
  toxic_ticket:
    container_name: toxic_ticket
    build:
      context: ./toxic_ticket
      dockerfile: Dockerfile
    image: server
    profiles: ["toxicticket"]
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      DB_NAME: default
    ports:
      - "5000:5000"
    volumes:
      - ./toxic_ticket:/app
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    profiles: ["frontend"]
    image: react
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
