version: '3'

services:
  backend:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      DB_NAME: default
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    profiles: ["messaging"]
    ports:
      - "6379:6379"

  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    profiles: ["frontend"]
    image: react
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
